script:
- bash ./scripts/refresh.sh
- bash ./scripts/update.sh
env:
  global:
  - GH_REF: github.com/doshprompt/highmaps-map-collection.git
  - secure: mJPmAB5AyTFsrBKivRCoOJ/zGcTIaabjHdieogVYA10fhpacpbUhGlRVHlI3wcsPOGk1T9k5lnuLb0abGiAnnnUWU8rJ2pKR1sVuwtyYSkQuMZdCKmqkblyWP4mI1aQmnRCZhkN9IDkzjU/jlQud6K4n3hG3STcp+LC6EE4BnSFv2Vw2kZcV9dWIJLVoYaGiqU44P2FaGE6TwwRKvIFoumm9MKteYrlW+mAkaNjQPa5w+sslE+Z7CVgzJWEdfcM236cPynZdIxrfWL0FZ3etsYPg/Z0EYciQn8oG2CFY8K8V+M2bvEKxv0TsWRXzNpXCpYOOyFngRnrMz1vZ1dG4CfqXpGJX2D0jUppzF7UPp/HY4pOCWgDB/7/7EPvG4nhy6Emf7Li0cWf6pXvm/PWVLQYxAbGfCELIS9fic5sGZCUA2gVi2i5m4NSy+uLUZY+XZq3DTjK9LNdpYveG581IIOXuE8n211cU4FN4gUtacp0tHE3Hy4ad2+6n6mkuxLdAMuGu99ve12xe8R/UhkPVCQkCqd20Rilad23rEUV1sQWC4Xjq03SmtwPdgCruiXKPf9oyCQ8oAQUc9yrmHafdP1ZI2Gmxfsf+bqFCFA4KGW2aWh93GIimTVbqvTTtOYenARJprEkRbpxVToNquRAv6hZGbDiSThB1+a+SlJALYmM=
